#!/usr/bin/env bash

set -u
set -e

# gumがインストールされていなければ終了
if ! type gum &> /dev/null; then
  echo "gum(https://github.com/charmbracelet/gum) is not installed"
  echo "please install it"
  echo "  brew install gum"
  echo "  go install github.com/charmbracelet/gum@latest"
  exit
fi

RED="#e33400"
ORANGE="#e39400"
GREEN="#5ccc96"
YELLOW="#f2ce00"
PURPLE="#b3a1e6"
PURPLE2="#7a5ccc"
DARK_PURPLE="#30365F"
DARK_PURPLE2="#686f9a"
CYAN="#00a3cc"
MAGENTA="#ce6f8f"
BACKGROUND="#0f111b"
FOREGROUND="#ecf0c1"
VISUAL_SELECTION="#1b1c36"
CURSOR_LINE="#16172d"
GREY="#818596"
GREY2="#c1c3cc"
PURE_WHITE="#ffffff"
PURE_BLACK="#000000"

print() {
  gum style --foreground "$FOREGROUND" "$1"
}
success() {
  gum style --foreground "$CYAN" "$1"
}
error() {
  gum style --foreground "$RED" "$1"
}
br(){
  echo
}
input() {
  gum input "$@"
}
choose() {
  gum choose "$@"
}

gum style --foreground "$YELLOW" --bold "New Article"

TITLE=$(input --prompt "article title? ")
if test -n "$TITLE" ;then
  print "title: $TITLE"
else
  error "Title missing"
  exit
fi

SLUG=$(input --prompt "slug? ")
if test -n "$SLUG" ;then
  print "slug: $SLUG"
else
  error "Slug missing"
  exit
fi

TYPE=$(choose "tech" "idea" "neco")
if test -n "$TYPE" ;then
  print "type: $TYPE"
else
  error "Type missing"
  exit
fi

COMMAND="npx zenn new:article --slug "$SLUG" --title "$TITLE" --type "$TYPE""
STYLED_COMMAND=$(gum style --background "$BACKGROUND" --foreground "$YELLOW" -- "${COMMAND}")

if gum confirm "Execute ${STYLED_COMMAND}?"; then
  npx zenn new:article --slug "$SLUG" --title "$TITLE" --type "$TYPE"
  success "completed!"
else
  error "exit"
fi
