#!/usr/bin/env bash

set -e

title=$(gum input --placeholder "title?")

if test "$title" == ""; then
	echo "タイトルを入力してください"
	exit
fi

deno run --no-lock --reload -A npm:zenn-cli@latest new:article --title "$title"
