#!/usr/bin/env bash

set -e

article=$(deno run --no-lock --reload -A npm:zenn-cli@latest list:articles | fzf)
article_file=$(echo "$article" | awk '{ print $1 ".md" }')

command nvim ./articles/"$article_file"
