#!/usr/bin/env bash

set -e

article=$(deno run -A npm:zenn-cli@latest list:articles | fzf)

[ -z "$article" ] && exit 1

article_file=$(echo "$article" | awk '{ print $1 ".md" }')

command nvim ./articles/"$article_file"
